export const addUser='/store'
export const viewDetails='/show'
export const deleteUser='/delete'
export const updateDetails='/update'
export const registerUser='/register'
export const signInUser='/sign-in'